stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "unix:///var/run/docker.sock"  # локальный сокет Docker

build-job:
  stage: build
  image: node:22.11.0
  before_script:
    - cd $CI_PROJECT_DIR
    - git pull origin dev
  script:
    - docker build -t 1009_front_dev:latest .
  only:
    - dev

deploy-job:
  stage: deploy
  script:
    - docker stop 1009_front_dev || true
    - docker rm 1009_front_dev || true
    - docker run -d --name 1009_front_dev -p 3000:3000 1009_front_dev:latest
    - docker image prune -f
  only:
    - dev