export const API_MAP = {
  USERS: "user",
  CREATE_USER: "user",
  UPDATE_USER: "user",
  DELETE_USER: "user",
  ROLES: "role",
  LOG_IN: "user/log-in",
  MAIN_ORGANIZATION_ALL: "main-organization",
  CREATE_MAIN_ORGANIZATION: "main-organization",
  UPDATE_MAIN_ORGANIZATION: "main-organization",
  DELETE_MAIN_ORGANIZATION: "main-organization",
  PRODUCT_SERVICE_CATEGORY_ALL: "product-servise-category",
  CREATE_PRODUCT_SERVICE_CATEGORY: "product-servise-category",
  UPDATE_PRODUCT_SERVICE_CATEGORY: "product-servise-category",
  DELETE_PRODUCT_SERVICE_CATEGORY: "product-servise-category",
  PRODUCT_SERVICE_SUB_CATEGORY_ALL: "product-servise-sub-category",
  CREATE_PRODUCT_SERVICE_SUB_CATEGORY: "product-servise-sub-category",
  UPDATE_PRODUCT_SERVICE_SUB_CATEGORY: "product-servise-sub-category",
  DELETE_PRODUCT_SERVICE_SUB_CATEGORY: "product-servise-sub-category",
};
