export const STEPS_DATA = {
  FIRST_FORMDATA: [
    "abonent",
    "org-name",
    "category",
    "sub-category",
    "main-org",
    "secret",
  ],
  SECOND_FORMDATA: [
    "region",
    "city",
    "village",
    "district",
    "manage",
    "residential-area",
    "area",
    "kvartal",
    "street",
    "lane",
    "passage",
    "impasse",
    "address",
    "home",
    "apartment",
  ],
  FOURTH_FORMDATA: ["payment_type", "description"],
};

export const SEND_BODY = [
  "abonent",
  "org-name",
  "category",
  "sub-category",
  "main-org",
  "secret",
  "region",
  "city",
  "village",
  "district",
  "manage",
  "residential-area",
  "area",
  "kvartal",
  "street",
  "lane",
  "passage",
  "impasse",
  "address",
  "home",
  "apartment",
  "payment_type",
  "description",
];
